source:      .
destination: ./_site

domain: quang-truong.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://quang-truong.github.io  # the base hostname and protocol for your site, e.g. http://example.com

# Cache busting version - increment this when you want to force cache refresh
version: 1.0.2

collections:
  projects:
    output: true
