source:      .
destination: ./_site
includes:    ./_includes

domain: quang-truong.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://quang-truong.github.io  # the base hostname and protocol for your site, e.g. http://example.com

collections:
  projects:
    output: true
